### PR TITLE
Improved General Support instructions

### PR DESCRIPTION
**Pull request by garrettr**
r? @ageis @conorsch

### CODE REVIEW

**Comment by conorsch** [comment]
This is good as-is. Built the docs locally to view in rich text. I expected to want a change to the landing page, prior to linking out to the General Support page, but the text is clear and concise as it stands. :+1:!

**Comment by ageis** [comment]
@garrettr yo, you forgot to remove reference to Documents and Files!

**Comment by ageis** [comment]
@garrettr also, we should add a recommended username scheme. Like first letter of first name plus last name.

**Comment by garrettr** [comment]
@ageis Ah, those should go into separate pull requests though :) But thanks for reminding me, I'll take care of that right now.

**Comment by conorsch** [comment]
> Ah, those should go into separate pull requests though

:+1:, standing by for review

**Comment by ageis** [comment]
@conorsch already committed, uncontroversial changes

**Pull request merged**
