### PR TITLE
Step-by-step instructions for finding issues

### PR DESCRIPTION
**Pull request by garrettr**
Now with more screenshots!

### CODE REVIEW

**Comment by garrettr** [comment]
I realize that this creates a discrepancy between the screenshots for the user named "securedrop_admin" and this new user, "clarkk". I'm not sure if it matters all that much. If people think it does, I think we should standardize on a preferred user naming convention (e.g. clarkk or ckent) and re-do the screenshots to use that example name consistently.

I also think that that generic example names like "securedrop_admin" are not great because they encourage people to choose generic names, which is not very helpful to FPF staff who will have to interact with many different users simultaneously, and will benefit if it is easy to differentiate between them.

**Comment by garrettr** [comment]
@conorsch @ageis Review?

**Comment by ageis** [comment]
lgtm

**Comment by garrettr** [comment]
Double-checked that this renders correctly, it looks good, merging.

**Comment by conorsch** [comment]
:+1: 

As an aside, the superhero names lend a bit of much-needed levity to the support docs. Great choice for examples.

**Pull request merged**
